version: 0.2

phases:
  build:
    commands:
      - bash pipelines/ci.sh
  post_build:
    finally:
      # Create build status badge
      - |
        if [ $STAGE == "prd" ]; then
            if [ "$1" -ne 0 ]; then
                badge_status=failing
                badge_colour=red
            else
                badge_status=passing
                badge_colour=green
            fi
            curl -s "https://img.shields.io/badge/build-$badge_status-$badge_colour.svg" > "build-status.svg"
            aws s3 cp "build-status.svg" "s3://learn-common-words.net/build-status.svg" --cache-control no-cache
        fi
